update=Sat 14 Jan 2012 03:53:52 AM EET
last_client=cvpcb
[general]
version=1
[pcbnew]
version=1
PadDrlX=320
PadDimH=600
PadDimV=600
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
LastNetListRead=ruuvitracker.net
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=led
LibName10=dip_sockets
LibName11=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/gsm/SIM908
LibName12=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/mlp/MLP-8
LibName13=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/connectors/005INCH_PINSTRIP_THRUHOLE_6PIN
LibName14=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/connectors/005INCH_PINSTRIP_THRUHOLE_8PIN
LibName15=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/connectors/005INCH_PINSTRIP_THRUHOLE_12PIN
LibName16=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/lga/LGA-14
LibName17=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/connectors/005INCH_PINSTRIP_THRUHOLE_2PIN
LibName18=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/sot/SOT323-5L
LibName19=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/walter/w_smd_cap
LibName20=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/crystals/ABM3B_SMD_CRYSTAL
LibName21=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/usb/MICROUSB_B_473460001
LibName22=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/memcards/COMBO_CARDSLOT_MES3051
LibName23=/home/lauri/Projektit/kicad_lib_oma/pcb_modules/lqfp/LQFP-64
LibDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
